Repository BaseAdresseNationale/adresse.data.gouv.fr, pull requests merged in 2018-07, with the labels that each got.

#141 Amélioration de la recherche de commune
  components/bases-locales/init-base/index.js
  components/bases-locales/init-base/search-communes.js
  components/search-input/render-commune.js
Labels: bug

#152 Limite la hauteur des logos
  components/bases-locales/bases-adresse-locales/dataset/header.js
Labels: bal

#153 Ajout d'un tag pour les toponymes
  components/bases-locales/bases-adresse-locales/dataset/commune/index.js
  components/bases-locales/bases-adresse-locales/dataset/commune/voie/index.js
  components/bases-locales/bases-adresse-locales/dataset/commune/voie/voie-preview.js
  components/bases-locales/bases-adresse-locales/dataset/header.js
  components/bases-locales/bases-adresse-locales/dataset/index.js
  components/bases-locales/bases-adresse-locales/meta.js
  components/explorer/voie/address.js
  components/explorer/voie/infos.js
  components/tag.js
  lib/table.js
  lib/types.js
Labels: bal

#151 Suppression des polices personnalisées
  components/main-style.js
  components/styles/fonts.js
  static/fonts/Evolventa/Evolventa-Bold.woff
  static/fonts/Evolventa/Evolventa-BoldOblique.woff
  static/fonts/Evolventa/Evolventa-Oblique.woff
  static/fonts/Evolventa/Evolventa-Regular.woff
  static/fonts/SourceSansPro/SourceSansPro-Black.otf.woff
  static/fonts/SourceSansPro/SourceSansPro-Black.otf.woff2
  static/fonts/SourceSansPro/SourceSansPro-BlackIt.otf.woff
  static/fonts/SourceSansPro/SourceSansPro-BlackIt.otf.woff2
  static/fonts/SourceSansPro/SourceSansPro-Bold.otf.woff
  static/fonts/SourceSansPro/SourceSansPro-Bold.otf.woff2
  static/fonts/SourceSansPro/SourceSansPro-BoldIt.otf.woff
  static/fonts/SourceSansPro/SourceSansPro-BoldIt.otf.woff2
  static/fonts/SourceSansPro/SourceSansPro-ExtraLight.otf.woff
  static/fonts/SourceSansPro/SourceSansPro-ExtraLight.otf.woff2
  static/fonts/SourceSansPro/SourceSansPro-ExtraLightIt.otf.woff
  static/fonts/SourceSansPro/SourceSansPro-ExtraLightIt.otf.woff2
  static/fonts/SourceSansPro/SourceSansPro-It.otf.woff
  static/fonts/SourceSansPro/SourceSansPro-It.otf.woff2
  static/fonts/SourceSansPro/SourceSansPro-Light.otf.woff
  static/fonts/SourceSansPro/SourceSansPro-Light.otf.woff2
  static/fonts/SourceSansPro/SourceSansPro-LightIt.otf.woff
  static/fonts/SourceSansPro/SourceSansPro-LightIt.otf.woff2
  static/fonts/SourceSansPro/SourceSansPro-Regular.otf.woff
  static/fonts/SourceSansPro/SourceSansPro-Regular.otf.woff2
  static/fonts/SourceSansPro/SourceSansPro-Semibold.otf.woff
  static/fonts/SourceSansPro/SourceSansPro-Semibold.otf.woff2
  static/fonts/SourceSansPro/SourceSansPro-SemiboldIt.otf.woff
  static/fonts/SourceSansPro/SourceSansPro-SemiboldIt.otf.woff2
Labels: enhancement

#155 Ajout d'un zoom maximum pour l'affichage initial
  components/bases-locales/bases-adresse-locales/dataset/commune/voie/numeros-map.js
  components/mapbox-gl/index.js
Labels: bal

#160 Update next.js, generate changelogs
  .babelrc
  .circleci/config.yml
  .gitignore
  build/scripts/extract-bundles
  next.config.js
  package.json
  yarn.lock
Labels: build, performance

#161 Replace paragraphs with divs in Head component
  components/head.js
Labels: bug

#163 Update regenerator-runtime to 0.12.0
  package.json
  yarn.lock
Labels: bug, dependencies
