Repository BaseAdresseNationale/adresse.data.gouv.fr, pull requests merged in 2018-10, with the labels that each got.

#162 Remove Api component and move code to Api page
  components/api.js
  pages/api.js
Labels: cleanup

#171 Correction de l’annulation de changement d’un numéro
  components/bases-locales/editor/index.js
Labels: bug

#173 Corrige l'affichage des champs inconnus
  components/bases-locales/validator/report/index.js
  components/bases-locales/validator/report/line-value.js
  components/bases-locales/validator/report/line.js
  components/bases-locales/validator/report/row.js
  components/bases-locales/validator/report/rows.js
  package.json
  yarn.lock
Labels: bug, validateur bal

#178 Debounce sur auto-complétion nom de commune de l'initialisation BAL
  components/bases-locales/init-base/search-communes.js
Labels: bal
