Repository BaseAdresseNationale/adresse.data.gouv.fr, pull requests merged in 2019-02, with the labels that each got.

#252 Fix regenerator runtime issues
  components/bases-locales/editor/index.js
  components/bases-locales/editor/uploader.js
  components/bases-locales/validator/index.js
  package.json
  pages/bases-locales/editeur.js
  yarn.lock
Labels: cleanup

#251 Remove piwik-react-router
  .env.sample
  .gitignore
  components/meta.js
  layouts/main.js
  lib/explore/api.js
  lib/piwik.js
  next.config.js
  package.json
  pages/_app.js
  pages/_document.js
  yarn.lock
Labels: cleanup

#253 Update jest-related dependencies
  package.json
  yarn.lock
Labels: dependencies

#254 Update react to 16.7.0
  package.json
  yarn.lock
Labels: dependencies

#255 Improve webpack configuration
  next.config.js
Labels: cleanup

#257 Remove unsafe lifecycle in Csv and Geocoder components
  components/csv/csv.js
  components/csv/geocoder.js
Labels: cleanup

#258 Update @etalab/bal and @etalab/project-legal
  package.json
  yarn.lock
Labels: dependencies

#261 Amélioration du sélecteur de commune
  components/bases-locales/editor/edit-bal/init-base.js
  components/bases-locales/editor/edit-bal/search-communes.js
Labels: enhancement

#263 Corrige les problèmes de modèle Adresse
  lib/bal/item.js
  lib/geojson.js
Labels: bug

#273 Update React and dependencies
  package.json
  yarn.lock
Labels: dependencies

#274 Ajout du nombre de communes représentées dans les BAL
  components/bases-locales/index.js
Labels: enhancement

#284 Édition accessible directement depuis la carte
  components/bases-locales/editor/edit-bal/communes/communes-list.js
  components/bases-locales/editor/edit-bal/communes/index.js
  components/bases-locales/editor/edit-bal/context/commune/commune-context.js
  components/bases-locales/editor/edit-bal/context/commune/create-toponyme.js
  components/bases-locales/editor/edit-bal/context/commune/voie-form.js
  components/bases-locales/editor/edit-bal/context/commune/voie-item.js
  components/bases-locales/editor/edit-bal/context/commune/voies-list.js
  components/bases-locales/editor/edit-bal/context/index.js
  components/bases-locales/editor/edit-bal/context/numero-context.js
  components/bases-locales/editor/edit-bal/context/voie/create-numero.js
  components/bases-locales/editor/edit-bal/context/voie/empty-numeros-list.js
  components/bases-locales/editor/edit-bal/context/voie/numero-form.js
  components/bases-locales/editor/edit-bal/context/voie/numero-item.js
  components/bases-locales/editor/edit-bal/context/voie/numeros-list.js
  components/bases-locales/editor/edit-bal/context/voie/position-form.js
  components/bases-locales/editor/edit-bal/context/voie/positions-map.js
  components/bases-locales/editor/edit-bal/context/voie/select-position-type.js
  components/bases-locales/editor/edit-bal/context/voie/single-position-map.js
  components/bases-locales/editor/edit-bal/context/voie/toponyme-context.js
  components/bases-locales/editor/edit-bal/context/voie/voie-context.js
  components/bases-locales/editor/edit-bal/create-item-wrapper.js
  components/bases-locales/editor/edit-bal/index.js
  components/bases-locales/editor/edit-bal/prevented-default-form.js
  components/bases-locales/editor/edit-bal/text-input.js
  components/bases-locales/editor/index.js
  components/commune-visualizer/commune-map.js
  components/commune-visualizer/context-menu.js
  components/commune-visualizer/create-address-menu.js
  components/commune-visualizer/create-feature-menu.js
  components/commune-visualizer/create-position-menu.js
  components/commune-visualizer/edition-menu.js
  components/commune-visualizer/index.js
  components/commune-visualizer/voie-menu.js
  components/mapbox/filters.js
  components/mapbox/helpers.js
  components/mapbox/layers.js
  components/mapbox/map.js
  components/select.js
  lib/bal/__tests__/model.js
  lib/bal/item.js
  lib/bal/model.js
  lib/geojson.js
  package.json
  pages/bases-locales/editeur.js
  yarn.lock
Labels: bal
