Repository BaseAdresseNationale/adresse.data.gouv.fr, pull requests merged in 2019-04, with the labels that each got.

#328 Mise à jour des dépendances
  package.json
  yarn.lock
Labels: dependencies

#332 Nouvel outil de publication de Base Adresse Locale
  components/bases-locales/publication/authentification.js
  components/bases-locales/publication/form.js
  components/bases-locales/publication/manage-file.js
  components/bases-locales/publication/published.js
  components/bases-locales/publication/publishing.js
  components/bases-locales/publication/step.js
  components/bases-locales/publication/steps.js
  components/bases-locales/publication/user.js
  components/bases-locales/validator/file-handler.js
  components/bases-locales/validator/index.js
  components/button-link.js
  components/button.js
  lib/bal/api.js
  lib/bal/file.js
  lib/fetch.js
  next.config.js
  package.json
  pages/bases-locales/publication.js
  static/images/FCboutons-10.svg
  static/images/icons/elu.svg
  yarn.lock
Labels: bal, enhancement

#333 Page publication responsive
  components/bases-locales/publication/authentification.js
  components/bases-locales/publication/step.js
  components/bases-locales/publication/steps.js
Labels: design
