Repository BaseAdresseNationale/adresse.data.gouv.fr, pull requests merged in 2021-10, with the labels that each got.

#895 Corrections et améliorations de l'expérience utilisateur lors de la publication
  lib/bal/api.js
  pages/bases-locales/publication.js
Labels: bug, enhancement, bal

#897 Active helmet en production (sécurité)
  package.json
  server.js
  yarn.lock
Labels: security

#896 Suppression de la dépendance à unpkg.com
  package.json
  pages/_app.js
  pages/_document.js
  yarn.lock
Labels: dependencies
