Repository BaseAdresseNationale/adresse.data.gouv.fr, pull requests merged in 2021-06, with the labels that each got.

#815 Affichage des parcelles attribuées aux adresses sur la carte interactive BAN
  components/base-adresse-nationale/commune/details.js
  components/base-adresse-nationale/numero/index.js
  components/base-adresse-nationale/parcelles-list.js
  components/base-adresse-nationale/voie/index.js
  components/mapbox/ban-map/index.js
  components/mapbox/ban-map/layers.js
  components/mapbox/ban-map/popups.js
  components/mapbox/cadastre-layer-control.js
  components/mapbox/center-control.js
  components/mapbox/select-paint-layer.js
  pages/base-adresse-nationale.js
Labels: bal, enhancement

#828 Mise à jour du guide Mes Adresses
  pages/guides.js
Labels: bal, doc

#827 MAJ entrée FAQ fréquence de mise à jour
  pages/faq.js
Labels: doc

#830 Mise à jour de la librairie react-dropzone en version 11.3.2
  package.json
  yarn.lock
Labels: dependencies

#825 Modifcation de l'ordre d'affichage des dernières Base Adresse publiées
  components/bases-locales/bases-adresse-locales/index.js
Labels: bug

#826 Ouvrir une adresse dans un GPS et copie des coordonnées
  components/base-adresse-nationale/explorer.js
  components/base-adresse-nationale/numero/coordinates-copy.js
  components/base-adresse-nationale/numero/index.js
  components/button.js
  components/mapbox/ban-map/index.js
  components/mapbox/open-gps.js
  components/notification.js
  contexts/device.js
  jsconfig.json
  layouts/base-adresse-nationale.js
  pages/_app.js
  pages/base-adresse-nationale.js
Labels: enhancement
