Repository BaseAdresseNationale/adresse.data.gouv.fr, pull requests merged in 2022-04, with the labels that each got.

#1114 Supprime un partenaire dupliqué par erreur
  partners.json
Labels: bug

#1125 Encourager les communes à être référencée comme partenaire
  components/bases-locales/charte/search-partners-results.js
Labels: design

#1131 Redirection vers une formulaire de création de BAL prérempli pour la commune
  components/commune/bal-state.js
Labels: enhancement

#1136 Update @etalab/bal (2.4.0)
  package.json
  yarn.lock
Labels: dependencies

#1137 Corrige les erreurs 500 dans l’explorateur BAN
  components/base-adresse-nationale/numero/index.js
Labels: bug
