Repository BaseAdresseNationale/adresse.data.gouv.fr, pull requests merged in 2022-07, with the labels that each got.

#1218 Ajouter Quimperlé Communauté sur la page des partenaires de la charte
  partners.json
  public/images/logos/partners/epci/quimperle.png
Labels: partners

#1221 Ajout de la commune Entre-deux
  partners.json
  public/images/logos/partners/communes/entre-deux.png
Labels: partners

#1207 Accessibilité non-visuelle des liens et éléments interactifs
  components/api-doc/api-adresse/expandable-menu.js
  components/api-doc/api-adresse/technical-doc/attributs.js
  components/api-doc/api-adresse/technical-doc/path.js
  components/base-adresse-nationale/commune/tabs.js
  components/base-adresse-nationale/layout-selector.js
  components/base-adresse-nationale/postal-codes.js
  components/bases-locales/bases-adresse-locales/base-adresse-locale.js
  components/bases-locales/bases-adresse-locales/dataset/index.js
  components/bases-locales/bases-adresse-locales/summary.js
  components/bases-locales/charte/commune.js
  components/bases-locales/charte/dropdown.js
  components/bases-locales/charte/tags.js
  components/bases-locales/publication/authentification.js
  components/bases-locales/publication/code-authentification.js
  components/bases-locales/validator/report/summary/issue-dialog.js
  components/bases-locales/validator/report/summary/issue-rows.js
  components/bases-locales/validator/report/summary/row.js
  components/blog-card.js
  components/blog-pagination.js
  components/button-link.js
  components/card.js
  components/circle-link.js
  components/commune/contact-modal.js
  components/commune/historique-item.js
  components/evenement/event-banner.js
  components/evenement/event-modal.js
  components/evenement/event.js
  components/fantoir/body-list-fantoir.js
  components/fantoir/voie-information.js
  components/footer.js
  components/hamburger-menu.js
  components/hero.js
  components/mairie/mairie-schedules.js
  components/map-bal-section.js
  components/maplibre/select-paint-layer.js
  components/maplibre/switch-map-style.js
  components/question.js
  components/selectable-item-list.js
  components/social-media.js
  components/table-list/index.js
  components/table-list/table-control.js
  components/table-list/table/body.js
  components/table-list/table/head.js
  components/table-list/table/index.js
  lib/date.js
  pages/blog/index.js
Labels: accessibility

#1225 Amélioration design carte infos des communes partenaires
  components/bases-locales/charte/partner.js
  components/mairie/mairie-contact.js
  public/images/icons/scarf.svg
Labels: design, partners

#1233 Modification du logo partenaire Communauté de communes du Pont du Gard
  public/images/logos/partners/epci/ccpg.jpg
Labels: partners

#1227 Accessibilité : résolution des problèmes de contraste des textes
  components/bases-locales/bases-adresse-locales/info.js
  components/bases-locales/charte/tags.js
  components/bases-locales/publication/step.js
  components/card.js
  components/csv/step.js
  components/maplibre/switch-map-style.js
  pages/index.js
  styles/colors.js
  styles/theme.js
Labels: accessibility

#1241 Mise à jour du logo de blog dans le footer
  components/footer.js
  public/images/medias/blog.svg
  public/images/medias/medium.svg
Labels: design

#1246 Changement de l'url vers la Communauté d’agglomération de Saint-Quentin-en-Yvelines
  partners.json
Labels: partners

#1235 Affichage des noms de voie alternatifs
  .gitignore
  components/base-adresse-nationale/commune/index.js
  components/base-adresse-nationale/commune/voie.js
  components/base-adresse-nationale/languages-preview.js
  components/base-adresse-nationale/numero/index.js
  components/base-adresse-nationale/region-infos.js
  components/base-adresse-nationale/tooltip.js
  components/base-adresse-nationale/voie/index.js
  components/maplibre/ban-map/popups.js
  package.json
  public/images/icons/flags/bre.svg
  public/images/icons/flags/cos.svg
  public/images/icons/flags/eus.svg
  public/images/icons/flags/fra.svg
  public/images/icons/flags/gcf.svg
  public/images/icons/flags/gcr.svg
  public/images/icons/flags/gsw.svg
  public/images/icons/flags/ntr.svg
  public/images/icons/flags/oci.svg
  public/images/icons/flags/rcf.svg
  public/images/icons/flags/swb.svg
  scripts/build-available-flags.js
Labels: do-not-merge

#1253 Intégration de la langue régionale dans le validateur
  components/base-adresse-nationale/tooltip.js
  components/bases-locales/validator/report/fields/found-fields.js
Labels: enhancement, design
