Repository BaseAdresseNationale/adresse.data.gouv.fr, pull requests merged in 2022-02, with the labels that each got.

#1015 Mise à jour du validateur BAL
  components/bases-locales/publication/manage-file.js
  components/bases-locales/validator/index.js
  components/bases-locales/validator/report/summary/index.js
  components/bases-locales/validator/report/summary/issue-dialog.js
  components/bases-locales/validator/report/summary/issue-rows.js
  components/bases-locales/validator/report/summary/issues-sumup.js
  components/bases-locales/validator/report/summary/line-value.js
  components/bases-locales/validator/report/summary/line.js
  components/bases-locales/validator/report/summary/row-issues.js
  components/bases-locales/validator/report/summary/row.js
  package.json
  pages/contribuer.js
  yarn.lock
Labels: enhancement

#1001 Intégration de l'API de dépôt pour le formulaire Base Adresse Locale
  .env.sample
  components/bases-locales/publication/authentification.js
  components/bases-locales/publication/code-authentification.js
  components/bases-locales/publication/form.js
  components/bases-locales/publication/manage-file.js
  components/bases-locales/publication/published.js
  components/bases-locales/publication/publishing.js
  components/bases-locales/publication/step.js
  components/bases-locales/publication/steps.js
  components/bases-locales/publication/user.js
  components/csv/holder.js
  lib/api-backend-publication.js
  lib/api-depot.js
  lib/proxy-api-depot.js
  package.json
  pages/bases-locales/publication.js
  server/index.js
  server/proxy-api-depot.js
  server/w.js
  styles/colors.js
  styles/theme.js
  yarn.lock
Labels: enhancement, bal

#1019 Améliorations de la page commune
  components/commune/bal-state.js
  components/commune/download-adresses.js
  components/commune/historique-item.js
  components/commune/historique.js
  lib/api-depot.js
  pages/commune/[codeCommune].js
Labels: enhancement, design

#1037 Guide Mes Adresses Guide en v5.0
  pages/guides.js
Labels: enhancement, bal

#1045 Mise à jour du Guide des Bonnes Pratiques en v3.0
  pages/guides.js
Labels: doc

#1043 Correction erreur 500 page commune
  components/commune/bal-state.js
  components/commune/historique-item.js
Labels: bug

#1038 Ajout d'une page évènements
  components/evenement/event-modal.js
  components/evenement/event.js
  events.json
  pages/_app.js
  pages/evenements.js
  pages/index.js
  public/images/event-illustration.svg
  public/images/icons/event-adresselab.svg
  public/images/icons/event-formation.svg
  public/images/icons/event-partenaire.svg
Labels: enhancement, design
